local input_actions_manager = require("lib.input_actions_manager")

function init(self)
    msg.post(".", "acquire_input_focus")
    input_actions_manager.init()
end

function update(self, dt)
    input_actions_manager.update(dt)
end

function on_message(self, message_id, message, sender)
    input_actions_manager.on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
    input_actions_manager.on_input(action_id, action)
end